### ISSUE TITLE
Remove trailing spaces on entry fields

### ISSUE THREAD

**Issue by duglin** [btbd/ImageHub#2]
I'm often just copy-n-pasting repo names into the entry fields and sometimes the copy grabs an extra space, which means the search fails. Sometimes its hard to even notice the space is there so it takes a second to figure out why I didn't get any search results when I know the repo does exist. It would be nice if the code would remove leading and trailing spaces from the entry fields (namespace & search).

**Comment by btbd** [comment]
Should be fixed now.
