### ISSUE TITLE
tags retreival returning xdr 500 error - json: cannot unmarshal string into Go struct field Tag.image_id of type int

### ISSUE THREAD

**Issue by grooverdan** [btbd/ImageHub#4]
From example http://soaphub.org/imagehub/tags?i=library%2Fmariadb if I expand the repo to return tags, the xdr request:

<pre>
http://soaphub.org/imagehub/tags?i=library%2Fmariadb
<pre>

Returns a 500 status code with message body:

<pre>
json: cannot unmarshal string into Go struct field Tag.image_id of type int
</pre>

To reproduce:
<pre>
$ curl 'http://soaphub.org/imagehub/tags?i=library%2Fmariadb' -v -H 'User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Connection: keep-alive' -H 'Referer: http://soaphub.org/imagehub/?q=mariadb&n=library&p=1'
*   Trying 2607:f298:5:101d:f816:3eff:fe5f:4ac1:80...
*   Trying 208.97.140.135:80...
* Connected to soaphub.org (2607:f298:5:101d:f816:3eff:fe5f:4ac1) port 80 (#0)
> GET /imagehub/tags?i=library%2Fmariadb HTTP/1.1
> Host: soaphub.org
> Accept-Encoding: deflate, gzip, br
> User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0
> Accept: */*
> Accept-Language: en-US,en;q=0.5
> Connection: keep-alive
> Referer: http://soaphub.org/imagehub/?q=mariadb&n=library&p=1
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Server: nginx/1.13.12
< Date: Wed, 16 Sep 2020 21:16:39 GMT
< Content-Type: application/json
< Content-Length: 75
< Connection: keep-alive
< 
* Connection #0 to host soaphub.org left intact
<pre>

**Comment by btbd** [comment]
Fixed with latest commit.

**Comment by grooverdan** [comment]
Wow. Thanks for the great fix and much kudos for the response time.
